reference:
    dir: "GRCh38_rel90"
    url: "ftp://ftp.ensembl.org/pub/release-90/fasta/homo_sapiens/dna/Homo_sapiens.GRCh38.dna_sm.primary_assembly.fa.gz"
    gzipped_fasta: "GRCh38_rel90/Homo_sapiens.GRCh38.dna_sm.primary_assembly.fa.gz"
    fasta: "GRCh38_rel90/Homo_sapiens.GRCh38.dna_sm.primary_assembly.fa"

data:
    single-end:
        - SRR1097456

bismark-context:
    - 'CHG_OB'
    - 'CHG_OT'
    - 'CHH_OB'
    - 'CHH_OT'
    - 'CpG_OB'
    - 'CpG_OT'

digestion-site:
    mspl: 'C-CGG'
