# Snakefile for running bismark
configfile: "../config.yaml"

subworkflow reference_genome:
	workdir: "../reference_genome"
	snakefile: "../reference_genome/Snakefile"

subworkflow data:
	workdir: "../data"
	snakefile: "../data/Snakefile"

include: "rules/run.smk"

rule all:
	input:
		expand("result/{sample}/{context}_{sample}_bismark_bt2_se.txt.gz",
				sample=config['data']['single-end'],
				context=config['bismark-context'])
