# Snakefile for preparing sample short read data.
configfile: "../config.yaml"
include: "rules/prepare.smk"

rule all:
	input:
		expand("{sample}/{sample}.fastq.gz", sample=config['data']['single-end'])
